### ISSUE TITLE
Distribution "macosx_10_15_universal2" not working on macOS 14 ARM

### ISSUE THREAD

**Issue by tom-gangemi** [miute/pugixml-python#80]
Getting the following error trying to import pugixml after a `pip install pugixml` on macOS 14 ARM:

`ImportError: dlopen(venv311/lib/python3.11/site-packages/pugixml/pugi.cpython-311-darwin.so, 0x0002): tried: 'venv311/lib/python3.11/site-packages/pugixml/pugi.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))`

My guess is that build.yml needs MACOSX_DEPLOYMENT_TARGET set to "11" to properly build the universal dist.

Using "pip install --no-binary=:all: pugixml" resolves the issue locally.

**Comment by miute** [comment]
Fixed in #82 and #85.
